# Generated by Django 2.0.2 on 2018-04-29 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inflowco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=500, null=True)),
                ('ContractType', models.CharField(choices=[('d', 'DELIVERABLE BASED'), ('t', 'TIME BASED')], default='d', max_length=1)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('UrlSlug', models.SlugField()),
                ('ContractState', models.CharField(choices=[('c', 'Being Created'), ('u', 'Under Review'), ('r', 'Revisions Being Made'), ('n', 'Not Started'), ('p', 'In Progress'), ('x', 'Completed')], default='c', max_length=1)),
                ('Ownership', models.CharField(choices=[('i', 'I own this work'), ('u', 'Client owns this work')], default='i', max_length=1)),
                ('HourlyRate', models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True)),
                ('NumberOfAllowedRevisions', models.PositiveSmallIntegerField(default=1)),
                ('TotalContractWorth', models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True)),
                ('DownPaymentRate', models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True)),
                ('DownPaymentAmount', models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True)),
                ('ExtraRevisionFee', models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True)),
                ('RequestForChangeFee', models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True)),
                ('ChargeForLateReview', models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True)),
                ('KillFee', models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Contract',
            },
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=100)),
                ('FileURL', models.CharField(max_length=200)),
                ('FileExtension', models.CharField(max_length=10)),
                ('ContractForFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract')),
            ],
            options={
                'db_table': 'ContractFile',
            },
        ),
        migrations.CreateModel(
            name='ContractText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParagraphText', models.TextField(null=True)),
                ('Order', models.PositiveSmallIntegerField(default=1)),
                ('ContractFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract')),
            ],
            options={
                'db_table': 'ContractText',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('IdMilestone', models.AutoField(primary_key=True, serialize=False, verbose_name='IdMilestone')),
                ('Name', models.CharField(max_length=200)),
                ('Explanation', models.TextField()),
                ('MilestonePaymentAmount', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('EstimateHoursRequired', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('Deadline', models.DateField()),
                ('MilestoneState', models.CharField(choices=[('n', 'Not Started'), ('p', 'In Progress'), ('x', 'Completed')], default='n', max_length=1)),
                ('MilestoneContract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract')),
            ],
            options={
                'db_table': 'Milestone',
            },
        ),
        migrations.CreateModel(
            name='MilestoneFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=100)),
                ('FileURL', models.CharField(max_length=200)),
                ('FilePreviewURL', models.CharField(max_length=200)),
                ('FileExtension', models.CharField(max_length=10)),
                ('MilestoneForFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Milestone')),
            ],
            options={
                'db_table': 'MilestoneFile',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentDate', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ContractForPayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract')),
            ],
            options={
                'db_table': 'ContractPayment',
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentType', models.CharField(choices=[('o', 'ONE TIME'), ('w', 'WEEKLY'), ('b', 'BI WEEKLY'), ('m', 'MONTHLY')], default='o', max_length=1)),
                ('TotalPaymentAmount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ContractCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inflowco.Currency')),
                ('ContractForPaymentPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract', unique=True)),
            ],
            options={
                'db_table': 'ContractPaymentPlan',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('BillingName', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=20, null=True)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('ContractForRecipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract', unique=True)),
            ],
            options={
                'db_table': 'ContractRecipient',
            },
        ),
        migrations.CreateModel(
            name='RecipientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.CharField(max_length=200)),
                ('Address2', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=200)),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inflowco.Country')),
                ('RecipientForAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Recipient')),
            ],
            options={
                'db_table': 'ContractRecipientAddress',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RelationshipType', models.CharField(choices=[('f', 'FREELANCER'), ('c', 'CLIENT')], default='f', max_length=1)),
                ('ContractForRelationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract')),
                ('ContractUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ContractRelationship',
            },
        ),
    ]
