# Generated by Django 2.0.2 on 2018-04-29 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractfile',
            name='FileUploaded',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractfile',
            name='SizeOfFile',
            field=models.CharField(default='0 MB', max_length=10),
            preserve_default=False,
        ),
    ]
