# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inflowco', '0002_auto_20170925_0647'),
        ('contractsandprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ContractCurrency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inflowco.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='ContractType',
            field=models.CharField(choices=[('d', 'DELIVERABLE BASED'), ('t', 'TIME BASED')], default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='EndDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='PaymentType',
            field=models.CharField(choices=[('o', 'ONE TIME'), ('w', 'WEEKLY'), ('b', 'BI WEEKLY'), ('m', 'MONTHLY')], default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='RecipientAddress',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='RecipientCity',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='RecipientCountry',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='RecipientEmail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='RecipientName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='RecipientState',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='StartDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='UrlSlug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
