# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0002_auto_20171001_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('IdMilestone', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='IdMilestone')),
                ('Explanation', models.TextField()),
                ('MilestonePaymentAmount', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('MilestonePaymentType', models.CharField(choices=[('r', 'RAW AMOUNT'), ('p', 'PERCENTAGE')], default='r', max_length=1)),
                ('NumberOfAllowedRevisions', models.PositiveSmallIntegerField(default=1)),
                ('MilestoneContract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract')),
            ],
            options={
                'db_table': 'Milestone',
            },
        ),
    ]
