# Generated by Django 2.0.2 on 2018-04-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0002_auto_20180429_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractfile',
            name='FileUploaded',
        ),
        migrations.RemoveField(
            model_name='contractfile',
            name='SizeOfFile',
        ),
    ]
