# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractsandprojects', '0003_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RelationshipType', models.CharField(choices=[('f', 'FREELANCER'), ('c', 'CONTRACT')], default='f', max_length=1)),
                ('ContractUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ContractRelationship',
            },
        ),
        migrations.AlterField(
            model_name='milestone',
            name='IdMilestone',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='IdMilestone'),
        ),
    ]
