# Generated by Django 2.0.2 on 2018-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0003_auto_20180429_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractfile',
            name='FileUploaded',
            field=models.DateField(default='2018-04-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractfile',
            name='SizeOfFile',
            field=models.CharField(default='0 MB', max_length=10),
            preserve_default=False,
        ),
    ]
