# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0004_auto_20171005_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='ContractUser',
        ),
        migrations.AddField(
            model_name='relationship',
            name='ContractForRelationship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract'),
            preserve_default=False,
        ),
    ]
