# Generated by Django 2.0.2 on 2018-05-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0006_auto_20180511_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ChargeForLateReview',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ExtraRevisionFee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='KillFee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='RequestForChangeFee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
