# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0007_auto_20171006_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentDate', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ContractForPayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract')),
            ],
            options={
                'db_table': 'ContractPayment',
            },
        ),
    ]
