# Generated by Django 2.0.2 on 2018-06-09 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractsandprojects', '0007_auto_20180511_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('ReactionType', models.CharField(choices=[('a', 'Accept'), ('r', 'Reject')], default='a', max_length=1)),
                ('ReactionDateTime', models.DateTimeField()),
                ('MilestoneForReaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Milestone')),
                ('UserReacting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
