# Generated by Django 2.0.2 on 2018-04-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inflowco', '0004_emailsignup'),
        ('contractsandprojects', '0008_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.CharField(max_length=200)),
                ('Address2', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=200)),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inflowco.Country')),
            ],
            options={
                'db_table': 'ContractRecipientAddress',
            },
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='City',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='State',
        ),
        migrations.AddField(
            model_name='contract',
            name='ContractState',
            field=models.CharField(choices=[('c', 'Being Created'), ('n', 'Not Started'), ('u', 'Under Review'), ('r', 'Revisions Being Made'), ('p', 'In Progress'), ('x', 'Completed')], default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='Description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='Ownership',
            field=models.CharField(choices=[('i', 'I own this work'), ('u', 'Client owns this work')], default='i', max_length=1),
        ),
        migrations.AddField(
            model_name='recipient',
            name='BillingName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='EmailAddress',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='PhoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipientaddress',
            name='RecipientForAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Recipient'),
        ),
    ]
