# Generated by Django 2.0.2 on 2018-06-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0008_milestonereaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='milestonereaction',
            table='MilestoneReaction',
        ),
    ]
