# Generated by Django 2.0.2 on 2018-04-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0009_auto_20180408_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='MilestonePaymentType',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='NumberOfAllowedRevisions',
        ),
        migrations.AddField(
            model_name='contract',
            name='DownPaymentAmount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='DownPaymentRate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='HourlyRate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='NumberOfAllowedRevisions',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='TotalContractWorth',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='Deadline',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='EstimateHoursRequired',
            field=models.IntegerField(null=True),
        ),
    ]
