# Generated by Django 2.0.2 on 2018-04-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0010_auto_20180414_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='Name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
