# Generated by Django 2.0.2 on 2018-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0012_auto_20180414_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='EstimateHoursRequired',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
