# Generated by Django 2.0.2 on 2018-04-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0013_auto_20180415_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='Deadline',
            field=models.DateField(),
        ),
    ]
