# Generated by Django 2.0.2 on 2018-06-22 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractsandprojects', '0013_auto_20180617_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(max_length=50)),
                ('ChangeFrom', models.TextField()),
                ('ChangeTo', models.TextField()),
                ('ReasonForChange', models.TextField()),
                ('SystemGeneratedMessage', models.TextField()),
            ],
            options={
                'db_table': 'ContractAmendment',
            },
        ),
        migrations.CreateModel(
            name='ContractAmendmentSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateSubmitted', models.DateTimeField()),
                ('ContractAmended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract')),
                ('Proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ContractAmendmentSet',
            },
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='Set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.ContractAmendmentSet'),
        ),
    ]
