# Generated by Django 2.0.2 on 2018-04-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0014_auto_20180415_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ChargeForLateReview',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ExtraRevisionFee',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='KillFee',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='RequestForChangeFee',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
    ]
