# Generated by Django 2.0.2 on 2018-04-21 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0015_auto_20180415_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParagraphText', models.TextField(null=True)),
                ('Order', models.PositiveSmallIntegerField(default=1)),
                ('ContractFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract')),
            ],
            options={
                'db_table': 'ContractText',
            },
        ),
    ]
