# Generated by Django 2.0.2 on 2018-04-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0016_contracttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='MilestoneState',
            field=models.CharField(choices=[('n', 'Not Started'), ('p', 'In Progress'), ('x', 'Completed')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ContractState',
            field=models.CharField(choices=[('c', 'Being Created'), ('u', 'Under Review'), ('r', 'Revisions Being Made'), ('n', 'Not Started'), ('p', 'In Progress'), ('x', 'Completed')], default='c', max_length=1),
        ),
    ]
