# Generated by Django 2.0.2 on 2018-04-28 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractsandprojects', '0017_auto_20180425_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=100)),
                ('FileURL', models.CharField(max_length=200)),
                ('FileExtension', models.CharField(max_length=10)),
                ('ContractForFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Contract')),
            ],
            options={
                'db_table': 'ContractFile',
            },
        ),
        migrations.CreateModel(
            name='MilestoneFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=100)),
                ('FileURL', models.CharField(max_length=200)),
                ('FilePreviewURL', models.CharField(max_length=200)),
                ('FileExtension', models.CharField(max_length=10)),
                ('MilestoneForFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractsandprojects.Milestone')),
            ],
            options={
                'db_table': 'MilestoneFile',
            },
        ),
    ]
