# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 20:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active', models.BooleanField(default=True, verbose_name='Active')),
                ('Joined', models.DateTimeField(default=datetime.datetime(2017, 9, 20, 20, 39, 54, 678730, tzinfo=utc), verbose_name='Joined')),
                ('IdAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'UserSettings',
            },
        ),
    ]
