# Generated by Django 2.0.2 on 2018-04-29 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inflowco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SettingName', models.TextField()),
            ],
            options={
                'db_table': 'NotificationSetting',
            },
        ),
        migrations.CreateModel(
            name='UserAssociatedTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='IdAccount')),
            ],
            options={
                'db_table': 'UserAssociatedTypes',
            },
        ),
        migrations.CreateModel(
            name='UserGoogleInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoogleProfileID', models.CharField(max_length=50)),
                ('GoogleProfileName', models.CharField(max_length=150)),
                ('GoogleImageUrl', models.CharField(max_length=255)),
                ('UserAccount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='IdAccount')),
            ],
            options={
                'db_table': 'UserGoogleInformation',
            },
        ),
        migrations.CreateModel(
            name='UserLinkedInInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LinkedInProfileID', models.CharField(max_length=50)),
                ('LinkedInAccessToken', models.CharField(max_length=1000)),
                ('UserAccount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='IdAccount')),
            ],
            options={
                'db_table': 'UserLinkedInInformation',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Selected', models.BooleanField()),
                ('Setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.NotificationSetting')),
                ('UserAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='IdAccount')),
            ],
            options={
                'db_table': 'UserNotificationSettings',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCharged', models.DateField(verbose_name='DateCharged')),
                ('NextBillingDate', models.DateField(verbose_name='NextBillingDate')),
                ('PaymentLevel', models.CharField(choices=[('s', 'standard')], default='s', max_length=1)),
                ('PaymentAmount', models.DecimalField(decimal_places=2, default=16.0, max_digits=6, verbose_name='PaymentAmount')),
                ('UserAccount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='IdAccount')),
            ],
            options={
                'db_table': 'UserPaymentHistory',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentLevel', models.CharField(choices=[('s', 'standard')], default='s', max_length=1)),
                ('UrlSlug', models.SlugField(null=True)),
                ('StripeApiCustomerKey', models.CharField(max_length=30, null=True)),
                ('StripeConnectAccountKey', models.CharField(max_length=30, null=True)),
                ('FreelancerFrequency', models.CharField(choices=[('f', 'Full-Time'), ('p', 'Part-Time'), ('n', 'Not currently freelancing')], default='n', max_length=1)),
                ('FreelancerWorkWith', models.CharField(choices=[('s', 'Me, myself, and I'), ('t', 'Studio/team')], default='s', max_length=1)),
                ('FreelancerInterestedIn', models.CharField(choices=[('m', 'Milestone Tracking'), ('p', 'Proposals and Contracts'), ('i', 'Invoices'), ('a', 'All of them')], default='a', max_length=1)),
                ('BusinessName', models.CharField(max_length=50, null=True)),
                ('Region', models.CharField(max_length=50, null=True)),
                ('PhoneNumber', models.CharField(max_length=20, null=True)),
                ('BaseCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inflowco.Country', verbose_name='IdBaseCountry')),
                ('UserAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='IdAccount')),
            ],
            options={
                'db_table': 'UserSettings',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'UserType',
            },
        ),
        migrations.AddField(
            model_name='userassociatedtypes',
            name='UserFreelanceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserType'),
        ),
    ]
