# Generated by Django 2.0.2 on 2018-05-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='ZipCode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
