# Generated by Django 2.0.2 on 2018-05-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersettings_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='OtherType',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='FreelancerWorkWith',
            field=models.CharField(choices=[('s', 'Me, myself, and I'), ('t', 'Studio/team'), ('b', 'Both')], default='s', max_length=1),
        ),
    ]
