# Generated by Django 2.0.2 on 2018-05-13 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20180513_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest', models.CharField(choices=[('m', 'Milestone Tracking'), ('p', 'Proposals and Contracts'), ('i', 'Invoices'), ('a', 'All of them')], max_length=1)),
                ('UserAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='IdAccount')),
            ],
            options={
                'db_table': 'UserInterest',
            },
        ),
    ]
