# Generated by Django 2.0.2 on 2018-05-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='FreelancerInterestedIn',
        ),
    ]
