# Generated by Django 2.0.2 on 2018-05-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_inflowinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflowinvitation',
            name='GUID',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
