# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inflowco', '0001_initial'),
        ('accounts', '0010_auto_20170920_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='BaseCurrency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inflowco.Currency', verbose_name='IdBaseCurrency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='Joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 21, 20, 34, 42983, tzinfo=utc), verbose_name='Joined'),
        ),
    ]
