# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 21:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20170920_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='UserAccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='IdAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='Joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 21, 21, 43, 525355, tzinfo=utc), verbose_name='Joined'),
        ),
    ]
