# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20170920_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCharged', models.DateTimeField(verbose_name='DateCharged')),
                ('NextBillingDate', models.DateTimeField(verbose_name='NextBillingDate')),
                ('PaymentLevel', models.CharField(choices=[('s', 'standard')], default='s', max_length=1)),
                ('UserAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='IdAccount')),
            ],
            options={
                'db_table': 'UserPaymentHistory',
            },
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='Joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Joined'),
        ),
    ]
