# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170927_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='UrlSlug',
            field=models.SlugField(null=True),
        ),
    ]
