# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inflowco', '0003_country'),
        ('accounts', '0017_usersettings_stripeconnectaccountkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='BaseCountry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inflowco.Country', verbose_name='IdBaseCountry'),
            preserve_default=False,
        ),
    ]
