# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_usersettings_basecountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='BaseCurrency',
        ),
    ]
