# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_usersettings_basecurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='LinkedInAccessToken',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
