# Generated by Django 2.0.2 on 2018-02-18 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0022_usergoogleinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssociatedTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='IdAccount')),
            ],
            options={
                'db_table': 'UserAssociatedTypes',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'UserType',
            },
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='Joined',
        ),
    ]
