# Generated by Django 2.0.2 on 2018-02-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20180218_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassociatedtypes',
            name='UserFreelanceType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserType', unique=True),
            preserve_default=False,
        ),
    ]
