# Generated by Django 2.0.2 on 2018-02-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20180218_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='FreelancerFrequency',
            field=models.CharField(choices=[('f', 'Full-Time'), ('p', 'Part-Time'), ('n', 'Not currently freelancing')], default='n', max_length=1),
        ),
    ]
