# Generated by Django 2.0.2 on 2018-02-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_usersettings_freelancerfrequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='FreelancerInterestedIn',
            field=models.CharField(choices=[('m', 'Milestone Tracking'), ('p', 'Proposals and Contracts'), ('i', 'Invoices'), ('a', 'All of them')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='FreelancerWorkWith',
            field=models.CharField(choices=[('s', 'Me, myself, and I'), ('t', 'Studio/team')], default='s', max_length=1),
        ),
    ]
