# Generated by Django 2.0.2 on 2018-04-06 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_usersettings_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassociatedtypes',
            name='UserAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='IdAccount'),
        ),
        migrations.AlterField(
            model_name='userassociatedtypes',
            name='UserFreelanceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserType'),
        ),
    ]
