from django.conf.urls import url
from . import views

app_name = "htmldemos"
urlpatterns = [
    url(r'^$', views.DemoLoginView.as_view(), name='demo_home'),
    url(r'^welcome', views.DemoWelcome.as_view(), name='demo_welcome'),
    url(r'^address', views.DemoAddress.as_view(), name='demo_address'),
    url(r'^congratulations', views.DemoCongratulation.as_view(), name='demo_congratulation'),
    url(r'^stripe-connect', views.DemoStripeConnect.as_view(), name='demo_stripe_connect'),
    url(r'^stripe-thanks', views.DemoStripeThanks.as_view(), name='demo_stripe_thanks'),
    url(r'^terms-of-use', views.DemoTermsOfUse.as_view(), name='demo_tos'),
    url(r'^myprojects/create-contract/freelancer-msg', views.DemoCreateContractFreelancer.as_view(), name='demo_create_contract_freelancer'),
    url(r'^myprojects/create-contract/client-msg', views.DemoCreateContractClient.as_view(), name='demo_create_contract_client'),
    url(r'^myprojects/create-contract/received-email', views.DemoCreateContractReceivedEmail.as_view(), name='demo_create_contract_received_email'),
    url(r'^myprojects/create-contract/client-email-signed', views.DemoCreateContractClientEmailSigned.as_view(), name='demo_create_contract_client_email_signed'),
    url(r'^myprojects/create-contract/client-email-revision', views.DemoCreateContractClientEmailRevision.as_view(), name='demo_create_contract_client_email_revision'),
    url(r'^myprojects/create-contract/freelance-email-signed', views.DemoCreateContractFreelanceEmailSigned.as_view(), name='demo_create_contract_freelance_email_signed'),
    url(r'^myprojects/create-contract/freelance-email-revision', views.DemoCreateContractFreelanceEmailRevision.as_view(), name='demo_create_contract_freelance_email_revision'),
    url(r'^myprojects/project-details/', views.DemoProjectDetails.as_view(), name='demo_project_details'),
    url(r'^myprojects/create-contract/', views.DemoCreateNewContract.as_view(), name='demo_create_contract'),
    url(r'^myprojects/amend-contract/', views.DemoAmendContract.as_view(), name='demo_amend_contract'),
    url(r'^myprojects/upload-milestone/', views.DemoUploadMilestone.as_view(), name='demo_upload_milestone'),
    url(r'^myprojects/upload-milestone-drag/', views.DemoUploadMilestoneDrag.as_view(), name='demo_upload_milestone_drag'),
    url(r'^myprojects/preview-milestone/', views.DemoPreviewMilestone.as_view(), name='demo_preview_milestone'),
    url(r'^myprojects/', views.DemoMyProjectsScreen.as_view(), name='demo_my_projects'),
    url(r'^client-active-use/specific-project/milestones/upload-idle', views.ClientActiveUseLoFiSpecificProjectMilestoneUploadIdle.as_view(), name='client_active_use_specific_project_milestones_upload_idle'),
    url(r'^client-active-use/specific-project/milestones/upload-progress', views.ClientActiveUseLoFiSpecificProjectMilestoneUploadProgress.as_view(), name='client_active_use_specific_project_milestones_upload_progress'),
    url(r'^client-active-use/specific-project/milestones/preview/note', views.ClientActiveUseLoFiSpecificProjectMilestonePreviewNote.as_view(), name='client_active_use_specific_project_milestones_preview_note'),
    url(r'^client-active-use/specific-project/milestones/preview', views.ClientActiveUseLoFiSpecificProjectMilestonePreview.as_view(), name='client_active_use_specific_project_milestones_preview'),
    url(r'^client-active-use/specific-project/milestones/schedule/confirm-now', views.ClientActiveUseLoFiSpecificProjectMilestoneScheduleDeliveryConfirmSendNow.as_view(), name='client_active_use_specific_project_milestones_schedule_send_now'),
    url(r'^client-active-use/specific-project/milestones/schedule/confirm', views.ClientActiveUseLoFiSpecificProjectMilestoneScheduleDeliveryConfirmSend.as_view(), name='client_active_use_specific_project_milestones_schedule_send'),
    url(r'^client-active-use/specific-project/milestones/schedule', views.ClientActiveUseLoFiSpecificProjectMilestoneScheduleDelivery.as_view(), name='client_active_use_specific_project_milestones_schedule'),
    url(r'^client-active-use/specific-project/milestones', views.ClientActiveUseLoFiSpecificProjectMilestone.as_view(), name='client_active_use_specific_project_milestones'),
    url(r'^client-active-use/specific-project/overview', views.ClientActiveUseLoFiSpecificProjectOverview.as_view(), name='client_active_use_specific_project_overview'),
    url(r'^client-active-use/specific-project/invoices', views.ClientActiveUseLoFiSpecificProjectInvoices.as_view(), name='client_active_use_specific_project_invoices'),
    url(r'^client-active-use/specific-project/files', views.ClientActiveUseLoFiSpecificProjectFiles.as_view(), name='client_active_use_specific_project_files'),
    url(r'^client-active-use/quick-view', views.ClientActiveUseLoFiQuickView.as_view(), name='client_active_use_quick_view'),
    url(r'^client-active-use/email-confirm/freelancer', views.ClientActiveUseLoFiSpecificProjectEmailConfirmFreelancer.as_view(), name='client_active_use_email_confirm_freelancer'),
    url(r'^client-active-use/email-confirm/client', views.ClientActiveUseLoFiSpecificProjectEmailConfirmClient.as_view(), name='client_active_use_email_confirm_client'),
    url(r'^client-active-use', views.ClientActiveUseLoFiHome.as_view(), name='client_active_use'),
    url(r'^contract-creation', views.CreateContractStepOneDemo.as_view(), name='contract_creation'),
]