# Generated by Django 2.0.2 on 2018-04-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('IdCountry', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='IdCountry')),
                ('Name', models.CharField(default='United States', max_length=100, verbose_name='Name')),
                ('Code', models.CharField(default='US', max_length=5, verbose_name='Code')),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('IdCurrency', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='IdCurrency')),
                ('Country', models.CharField(default='United States', max_length=100, verbose_name='Country')),
                ('Name', models.CharField(default='Dollar', max_length=100, verbose_name='Name')),
                ('Code', models.CharField(default='USD', max_length=100, verbose_name='Code')),
            ],
            options={
                'db_table': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='EmailSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.EmailField(max_length=254)),
                ('Group', models.CharField(choices=[('g', 'General'), ('b', 'Blog')], default='g', max_length=1)),
            ],
            options={
                'db_table': 'EmailSignups',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='PrimaryCurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inflowco.Currency', verbose_name='PrimaryCurrency'),
        ),
    ]
