# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('IdCurrency', models.AutoField(primary_key=True, serialize=False, verbose_name='IdCurrency')),
                ('Country', models.CharField(max_length=100, verbose_name='Country')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Code', models.CharField(max_length=100, verbose_name='Code')),
            ],
            options={
                'db_table': 'Currency',
            },
        ),
    ]
