# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflowco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Code',
            field=models.CharField(default='USD', max_length=100, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='Country',
            field=models.CharField(default='United States', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='IdCurrency',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='IdCurrency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='Name',
            field=models.CharField(default='Dollar', max_length=100, verbose_name='Name'),
        ),
    ]
