# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inflowco', '0002_auto_20170925_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('IdCountry', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='IdCountry')),
                ('Name', models.CharField(default='United States', max_length=100, verbose_name='Name')),
                ('Code', models.CharField(default='US', max_length=5, verbose_name='Code')),
                ('PrimaryCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inflowco.Currency', verbose_name='PrimaryCurrency')),
            ],
            options={
                'db_table': 'Country',
            },
        ),
    ]
